### ISSUE TITLE
Vulkan Support?

### ISSUE THREAD

**Issue by xHaVoK87** [haikarainen/kit#10]
Any plans on adding this? I've actually created a thread on Reddit. [Reddit /r/Linux_Gaming](https://www.reddit.com/r/linux_gaming/comments/4wcaxq/realistic_game_framework_compatible_with_linux/)

**Comment by vincegogh** [comment]
I HIGHLY doubt it. Firstly, the framework only really released a couple of days ago, so it's pretty unlikely that any sort of porting to anything is going to happen anytime soon. Porting to vulkan is a *massive* amount of work, that alone could easily double the size of the project. Not to mention the fact that supporting two graphics APIs in one engine can lead to all sorts of issues and nightmares (not to mention the fact that less people will use vulkan anyway) - there's a reason why even the biggest game companies usually just stick to dx11 when developing their own engines.

**Comment by haikarainen** [comment]
As @vincegogh mentions, it would be a ton of work. But not only this, the framework is actually very tightly knit to OpenGL by design. Also, I suspect that future versions of OpenGL might become implemented on top of Vulkan, which will bring most performance increases that Kit would gain from Vulkan. 

The answer for now (and the foreseeable future) is no. But I dont know what might happen later. It would be cool to play around with..
