### ISSUE TITLE
Fix the smart ptr issue

### ISSUE THREAD

**Issue by haikarainen** [haikarainen/kit#35]
Right now, shared_ptr is heavily abused. After some feedback, I think it makes sense to redo how memory and resources are handled in this framework. I don't have a solid plan yet, feel free to share your ideas here!

**Comment by haikarainen** [comment]
Smart pointers are now completely removed from Kit. 

As a side-effect, basically no proper resource-management exist.

**Comment by haikarainen** [comment]
Have added smart pointer based resource management for textures, materials, submeshes. Some more work to be done.

**Comment by lukesanantonio** [comment]
When I was working on the engine I created a bunch of kinda weird smart pointers that you may find interesting. I'm not sure if they help your use case at all but the two biggies were a "peer pointer" and a "maybe owned." The peer pointer supported resource management when lua scripting was used, which you may have solved already. Basically the memory was held as long as every peer is kept alive. I gave one peer to Lua and another to the engine. As soon as one of them is destructed, the resource is disposed of, etc. It's sorta like an over-engineered shared_ptr and weak_ptr, I suppose. The maybe owned is just a pointer that is owned by one instance, it can be moved around between instances but the owner has the power to destruct it for everyone else, except when a lock is used to keep the resource alive for the lifetime of that lock. Anyways I thought you might be interested since you still seem to be working on resource management. Here's the repo with the source (https://github.com/lukesanantonio/UnusualSmartPointers) if you want to check it out. Good luck!

**Comment by haikarainen** [comment]
@lukesanantonio Sounds pretty much exactly like what shared_ptr and weak_ptr offers, just different names for them.

Anyway, I've already kind of decided on how I want to approach this, and I really want to stick with STL for these things. Thanks though!

**Comment by haikarainen** [comment]
This is done since long, however it is in a hidden repo as Kit is now more of a commercial product, and also a full-fledged engine.
